// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM-WIUMfAs_ldO2GPDDdHh-Oq9nz3AoHE',
    appId: '1:703312844686:web:d1607ab492c45d388436df',
    messagingSenderId: '703312844686',
    projectId: 'weather-social-app-bd759',
    authDomain: 'weather-social-app-bd759.firebaseapp.com',
    storageBucket: 'weather-social-app-bd759.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADDyZuGZHpPTMmsws_VxPsKtT7cYg5TPc',
    appId: '1:703312844686:android:11623728d22567a18436df',
    messagingSenderId: '703312844686',
    projectId: 'weather-social-app-bd759',
    storageBucket: 'weather-social-app-bd759.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPejNMHQAaevmfjawphsOkuqIaKVzFTQI',
    appId: '1:703312844686:ios:bb6e9f4f605799a48436df',
    messagingSenderId: '703312844686',
    projectId: 'weather-social-app-bd759',
    storageBucket: 'weather-social-app-bd759.firebasestorage.app',
    iosBundleId: 'com.example.weatherSocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPejNMHQAaevmfjawphsOkuqIaKVzFTQI',
    appId: '1:703312844686:ios:bb6e9f4f605799a48436df',
    messagingSenderId: '703312844686',
    projectId: 'weather-social-app-bd759',
    storageBucket: 'weather-social-app-bd759.firebasestorage.app',
    iosBundleId: 'com.example.weatherSocialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM-WIUMfAs_ldO2GPDDdHh-Oq9nz3AoHE',
    appId: '1:703312844686:web:92b5a01456bb95fd8436df',
    messagingSenderId: '703312844686',
    projectId: 'weather-social-app-bd759',
    authDomain: 'weather-social-app-bd759.firebaseapp.com',
    storageBucket: 'weather-social-app-bd759.firebasestorage.app',
  );
}
